#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/vmmgr
  
  rm -rf build/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ src/vmmgr src/vm_init src/vm_kill src/vm_launch src/vm_list src/vm_scrub src/vm_update src/vm_verify tests/test_setup.py setup.py
else
  echo "DEV_BASE is not defined"
fi
