#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/vmmgr
  
  autopep8 -ai -r vmmgr 
  autopep8 -ai vm_init vm_kill vm_launch vm_list vm_scrub vm_update vm_verify *.py
  
else
  echo "DEV_BASE is not defined"
fi
