#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/vmmgr
  
  autopep8 -ai -r vmmgr vmInit vmKill vmLaunch vmList vmScrub vmUpdate vmVerify *.py
  
else
  echo "DEV_BASE is not defined"
fi
