[meta]
version = "0.1.0"

[project]
name = "vmmgr"
package = "vmmgr"
main_lang = "py"
version = "0.5.21"
version_date = "2018-03-08"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
description = "tools for managing VMs in EC2 cloud"
copyright = "2014-2017"
dev_status = "pre_alpha"
license = "mit"
relpath = "py/vmmgr"
state = "shared"
url = "https://jddixon.github.io/vmmgr"

[py]
packages = [ "vmmgr",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = [ "src/vm_init", "src/vm_kill", "src/vm_launch", "src/vm_list", "src/vm_scrub", "src/vm_update", "src/vm_verify",]
ext_modules = []
distshare = [ "optionz",]
env_vars = []
requirements = [ "setuptools",]
test_requirements = [ "boto3", "botocore",]
